import { Qr } from "./qr";

export type CertificateProps = {
  recipient: string;
  nameAm?: string | null;
  title: string;
  details?: string | null;
  statement?: string | null;
  conferredLabel?: string;
  conferredDate: string;
  issuedDate: string;
  credId: string;
  verifyUrl: string;
  institution: string;
  institutionAm?: string | null;
  department?: string | null;
  initials: string;
  signatories: { name: string; title: string }[];
  /** Rendered width in px; the design's 1123 × 794 page is scaled to fit. */
  w?: number;
};

function signatureOf(name: string) {
  const parts = name.replace(/^(dr|prof|eng)\.?\s+/i, "").trim().split(/\s+/);
  return parts.length > 1 ? `${parts[0][0]}. ${parts[parts.length - 1]}` : parts[0];
}

/**
 * HTML rendition of the issued certificate, used for the live preview while issuing and on the credential page.
 * It follows the design's certificate layout; the downloadable PDF is generated by the API with the same structure.
 */
export function Certificate(p: CertificateProps) {
  const w = p.w ?? 1123;
  const k = w / 1123;
  const micro = Array(12).fill(`MAHTEM SEALED RECORD · ${p.credId} · `).join("");
  const sigs = p.signatories.slice(0, 2);
  return (
    <div style={{ width: w, height: Math.round(794 * k), overflow: "hidden", flex: "none" }} data-certificate>
      <div
        style={{
          width: 1123,
          height: 794,
          transform: `scale(${k})`,
          transformOrigin: "0 0",
          background: "#fbf9f7",
          position: "relative",
          color: "#201e1d",
          boxSizing: "border-box",
          padding: "58px 64px 52px",
          display: "flex",
          flexDirection: "column",
        }}
      >
        <div style={{ position: "absolute", inset: 22, border: "2px solid #7c1405", pointerEvents: "none" }} />
        <div style={{ position: "absolute", inset: 28, border: "1px solid #7c1405", opacity: 0.45, pointerEvents: "none" }} />
        <div style={{ display: "flex", alignItems: "flex-start", gap: 20 }}>
          <div style={{ width: 72, height: 72, border: "2px solid #201e1d", display: "grid", placeItems: "center", fontWeight: 800, fontSize: 20, flex: "none" }}>{p.initials}</div>
          <div style={{ display: "flex", flexDirection: "column", gap: 2, paddingTop: 2 }}>
            <div style={{ fontSize: 24, fontWeight: 800, letterSpacing: ".06em", textTransform: "uppercase", lineHeight: 1.1 }}>{p.institution}</div>
            {p.institutionAm && <div className="ethiopic" style={{ fontSize: 17, fontWeight: 600 }}>{p.institutionAm}</div>}
            {p.department && <div style={{ fontSize: 13, color: "#605d5d" }}>{p.department}</div>}
          </div>
          <div style={{ marginLeft: "auto", display: "flex", alignItems: "center", gap: 14 }}>
            <div style={{ display: "flex", flexDirection: "column", alignItems: "flex-end", gap: 2 }}>
              <div style={{ fontSize: 10, letterSpacing: ".14em", textTransform: "uppercase", color: "#605d5d" }}>Certificate No.</div>
              <div className="mono" style={{ fontWeight: 600, fontSize: 14 }}>{p.credId}</div>
            </div>
            <svg width="64" height="64" viewBox="0 0 64 64" aria-hidden="true">
              <rect x="1" y="1" width="62" height="62" fill="none" stroke="#7c1405" strokeWidth="2" strokeDasharray="3 2.2" />
              <rect x="8" y="8" width="48" height="48" fill="#7c1405" />
              <path d="M20 44V21l12 13 12-13v23" fill="none" stroke="#fbf9f7" strokeWidth="4" />
            </svg>
          </div>
        </div>
        <div style={{ height: 2, background: "#201e1d", margin: "26px 0 0" }} />
        <div style={{ flex: 1, display: "flex", flexDirection: "column", justifyContent: "center", gap: 6 }}>
          <div style={{ fontSize: 16, color: "#444141" }}>This is to certify that</div>
          <div style={{ fontSize: p.recipient.length > 30 ? 52 : 62, fontWeight: 800, letterSpacing: "-.025em", lineHeight: 1 }}>{p.recipient || "Recipient name"}</div>
          {p.nameAm && <div className="ethiopic" style={{ fontSize: 22, color: "#444141" }}>{p.nameAm}</div>}
          {p.statement && <div style={{ fontSize: 16, color: "#444141", marginTop: 14, maxWidth: 640, lineHeight: 1.45 }}>{p.statement}</div>}
          <div style={{ fontSize: 32, fontWeight: 600, color: "#7c1405", letterSpacing: "-.01em", lineHeight: 1.15 }}>{p.title || "Credential title"}</div>
          {p.details && <div style={{ fontSize: 16, fontWeight: 600 }}>{p.details}</div>}
        </div>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1.25fr 1.25fr 1.5fr", borderTop: "2px solid #201e1d" }}>
          <div style={{ padding: "14px 16px 0 0", borderRight: "1px solid #9b9797", display: "flex", flexDirection: "column", gap: 10 }}>
            <div>
              <div style={{ fontSize: 10, letterSpacing: ".12em", textTransform: "uppercase", color: "#605d5d" }}>{(p.conferredLabel ?? "Conferred")}</div>
              <div style={{ fontSize: 16, fontWeight: 600 }}>{p.conferredDate}</div>
            </div>
            <div>
              <div style={{ fontSize: 10, letterSpacing: ".12em", textTransform: "uppercase", color: "#605d5d" }}>Issued</div>
              <div style={{ fontSize: 16, fontWeight: 600 }}>{p.issuedDate}</div>
            </div>
          </div>
          {[0, 1].map((i) => {
            const s = sigs[i];
            return (
              <div key={i} style={{ padding: "6px 16px 0", borderRight: "1px solid #9b9797", display: "flex", flexDirection: "column", justifyContent: "flex-end" }}>
                <div className="script" style={{ fontSize: 44, lineHeight: 1, color: "#2d2b2b", height: 48 }}>{s ? signatureOf(s.name) : ""}</div>
                <div style={{ borderTop: "1px solid #201e1d", paddingTop: 6, fontSize: 13, fontWeight: 600 }}>{s?.name ?? " "}</div>
                <div style={{ fontSize: 11, color: "#605d5d" }}>{s?.title ?? " "}</div>
              </div>
            );
          })}
          <div style={{ padding: "14px 0 0 16px", display: "flex", gap: 14, alignItems: "flex-start" }}>
            <div style={{ width: 104, height: 104, flex: "none", border: "1px solid #201e1d" }}>
              <Qr text={p.verifyUrl} />
            </div>
            <div style={{ display: "flex", flexDirection: "column", gap: 4, minWidth: 0 }}>
              <div style={{ fontSize: 13, fontWeight: 800 }}>Scan to verify</div>
              <div style={{ fontSize: 11, color: "#444141", lineHeight: 1.4 }}>Point a phone camera at the code. No app needed.</div>
              <div className="mono" style={{ fontWeight: 600, fontSize: 10, color: "#7c1405", wordBreak: "break-all" }}>{p.verifyUrl.replace(/^https?:\/\//, "")}</div>
            </div>
          </div>
        </div>
        <div className="mono" style={{ position: "absolute", left: 30, right: 30, bottom: 31, fontWeight: 600, fontSize: 5.5, letterSpacing: ".18em", color: "#7c1405", opacity: 0.7, whiteSpace: "nowrap", overflow: "hidden" }}>{micro}</div>
      </div>
    </div>
  );
}
